#include <stdio.h>
#include <stdlib.h>
#include "sort_arr.h"				/* sort_arr.h generated by rpcgen */

int main(int argc, char *argv[]){
	CLIENT *clnt;
	struct list *result;
	char *server;

	struct list obj = {};
 
	if (argc < 4) {
		fprintf(stderr, "usage: %s host num1 num2 ... num N\n", argv[0]);
		exit(1);
	}
 
	server = argv[1];
	clnt = clnt_create(server, SORTPROG, SORTARRVERS, "tcp");
	if (clnt == (CLIENT *)NULL) {
		clnt_pcreateerror(server);
		exit(1);
	}

	obj.nums.nums_len = argc-2;
	obj.nums.nums_val = (int *)calloc((argc-2), sizeof(int));
	for(int i=0; i<argc-2; i++)
		obj.nums.nums_val[i] = atoi(argv[i+2]);

	printf("%d\n", argc-2);
	for(int i=0; i<(argc-2); i++)
		printf("%d ", obj.nums.nums_val[i]);
	printf("\n");
	result = sort_1(&obj, clnt);
	if (result == NULL) {
		clnt_perror(clnt, server);
		exit(1);
	}
	printf("\nGot response from server\n");
	printf("%d\n", (result->nums).nums_len);
	for(int i=0; i<(result->nums).nums_len; i++)
		printf("%d ", (result->nums).nums_val[i]);

	clnt_destroy(clnt);
	return 0;
}