/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_ARR_H_RPCGEN
#define _SORT_ARR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct list {
	struct {
		u_int nums_len;
		int *nums_val;
	} nums;
};
typedef struct list list;

#define SORTPROG 0x20000001
#define SORTARRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SORT 1
extern  list * sort_1(list *, CLIENT *);
extern  list * sort_1_svc(list *, struct svc_req *);
extern int sortprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SORT 1
extern  list * sort_1();
extern  list * sort_1_svc();
extern int sortprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_list (XDR *, list*);

#else /* K&R C */
extern bool_t xdr_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_ARR_H_RPCGEN */
