/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sort_arr.h"

bool_t
xdr_list (XDR *xdrs, list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->nums.nums_val, (u_int *) &objp->nums.nums_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
